build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.1"
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda35

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% nipype pymvpa2"
  - activate test-environment
  # shablona content
  # - pip install coverage
  # - python setup.py install
  - pip install -r requirements.txt
  - pip install -e

# TODO: No idea
test_script:
  - mkdir for_test
  - cd for_test
  - py.test --pyargs shambrain --cov-report term-missing --cov=shambrain
